// Generated by https://github.com/juliettef/IconFontCppHeaders script GenerateIconFontCppHeaders.py for languages C and C++
// from https://raw.githubusercontent.com/ForkAwesome/Fork-Awesome/master/src/icons/icons.yml
// for use with https://github.com/ForkAwesome/Fork-Awesome/blob/master/fonts/forkawesome-webfont.ttf
#pragma once

#define ICON_FK_FOLDER_L 0xf07b
#define ICON_FK_CODE_L 0xf15b
#define ICON_FK_TEXT_L 0xf15c
#define ICON_FK_IMAGE_L 0xf1c5
#define ICON_FK_MODEL_L 0xf1b2

#define ICON_FOLDER "\xef\x81\xbb"
#define ICON_SOURCE "\xef\x85\x9b"
#define ICON_TEXT "\xef\x85\x9c"
#define ICON_IMAGE "\xef\x87\x85"
#define ICON_CUBE "\xef\x86\xb2"


